# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Switch Xcode
      run: sudo xcode-select -s /Applications/Xcode_14.3.1.app
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  build-linux:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: swift-actions/setup-swift@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
